name: Generate doc description
run-name: Generate doc description
on: [push]
jobs:
  update-doc:
    runs-on: ubuntu-latest
    env:
      GPT_URL: ${{ secrets.GPT_URL }}
      GPT_KEY: ${{ secrets.GPT_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script:docs
        run: |
          npm install
          npm run script:docs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📃 docs(content): edit by chatGPT"
